Repository equinor/flownet, pull requests merged in 2020-08, with the labels that each got.

#98 Rock and Aquifer allowed as optional keyword in config
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
Labels: enhancement

#104 Add new logo
  README.md
  docs/_static/flownet_logo.png
  docs/_static/flownet_logo.svg
  docs/_static/flownet_model.svg
  docs/introduction.rst
Labels: documentation

#108 Fixed bug where faults would be inserted as an uncertain parameter, when no faults were present
  src/flownet/ahm/_run_ahm.py
Labels: bug

#110 Fixed relperm parameter bug
  src/flownet/ahm/_run_ahm.py
Labels: bug

#106 Fixed bug where the config would be parsed incorrectly when no aquifer is defined
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
Labels: bug

#92 Correct shutting in of last production well
  src/flownet/data/from_flow.py
Labels: bug, invalid

#111 Phases in simulation model
  examples/norne_parameters.yml
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_relative_permeability.py
  tests/configs/norne_parameters.yml
Labels: enhancement

#123 Speed up ray tracing
  setup.py
  src/flownet/network_model/_network_model.py
  src/flownet/utils/raytracing.py
Labels: enhancement

#119 Overall timeout on ert run
  src/flownet/ahm/_assisted_history_matching.py
Labels: bug

#90 Add analysis workflow as optional
  src/flownet/ahm/_ahm_iteration_analytics.py
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/static/SAVE_ITERATION_ANALYTICS_WORKFLOW
  src/flownet/static/SAVE_ITERATION_ANALYTICS_WORKFLOW_JOB
  src/flownet/templates/ahm_config.ert.jinja2
Labels: bug, enhancement

#128 Add option to use model hull to steer node/connection generation
  .github/workflows/flownet.yml
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_mitchell.py
  tests/test_generate_connections.py
Labels: enhancement

#136 AllowNone for queue name
  src/flownet/config_parser/_config_parser.py
Labels: invalid

#134 Add Egg model as CI test
  .github/workflows/flownet.yml
Labels: enhancement

#137 Remove examples folder
  .github/workflows/flownet.yml
  examples/egg_parameters.yml
  examples/flow_model_import.py
Labels: maintenance

#138 Adding print statement while generating schedule file
  src/flownet/realization/_schedule.py
Labels: enhancement

#141 Fix WCONINJH template
  src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
Labels: bug

#132 Expose observation uncertainty to users via YAML configuration file
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/prediction/_run_pred.py
  src/flownet/templates/ahm_config.ert.jinja2
  src/flownet/templates/common_config.ert.jinja2
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
Labels: enhancement

#146 Add about page
  docs/_static/equinor-logo.svg
  docs/_static/sintef-logo.svg
  docs/_static/tno-logo.svg
  docs/about.rst
  docs/index.rst
Labels: documentation

#150 Add PR template and CHANGELOG.md
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation, maintenance

#152 Add CODEOWNERS and deploy docs on merge to master
  .github/CODEOWNERS
  .github/workflows/flownet.yml
Labels: maintenance
