Repository equinor/flownet, pull requests merged in 2020-10, with the labels that each got.

#199 Make FlowNet work with pyscal 0.6.x, and add possibility of using pyscal's SCALrecommendation
  CHANGELOG.md
  setup.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_relative_permeability.py
  src/flownet/realization/_render_realization.py
Labels: enhancement

#213 Fix crashing CI
  src/flownet/ert/_create_ert_setup.py
Labels: bug

#205 Add python 3.8 to github workflow
  .github/workflows/flownet.yml
  src/flownet/ahm/_run_ahm.py
Labels: maintenance

#215 Update link to Brugge dataset in docs
  docs/introduction.rst
Labels: documentation

#216 Refactor SUMMARY.inc and add vectors
  src/flownet/static/SUMMARY.inc
Labels: enhancement, maintenance

#221 Save config yaml file and content of 'pip freeze' in the output folder
  CHANGELOG.md
  src/flownet/ert/_create_ert_setup.py
Labels: enhancement

#197 Make perforation strategies time/state/change (plugs/straddles) aware
  .github/workflows/flownet.yml
  .pylintrc
  CHANGELOG.md
  setup.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/data/from_source.py
  src/flownet/data/perforation_strategy.py
  src/flownet/network_model/_network_model.py
  src/flownet/realization/_schedule.py
  tests/test_perforation_strategies.py
Labels: blocked, enhancement

#224 Fix relative errors in yamlobs file
  src/flownet/templates/observations.yamlobs.jinja2
Labels: bug

#155 Kriging using well logs to constrain permeability and porosity parameter distributions in flow tubes
  CHANGELOG.md
  setup.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/data/from_source.py
  src/flownet/network_model/_network_model.py
  src/flownet/utils/kriging.py
Labels: enhancement
