Repository equinor/flownet, pull requests merged in 2020-03, with the labels that each got.

#8 Fixed logunif-error in norne_parameters.yml
  examples/norne_parameters.yml
Labels: bug

#2 Use GitHub workflows as CI
  .github/workflows/flownet.yml
  .travis.yml
  README.md
  build_environment.sh
Labels: enhancement

#11 Deploy GitHub pages on merge to master
  .github/workflows/flownet.yml
Labels: documentation
