Repository equinor/flownet, pull requests merged in 2020-09, with the labels that each got.

#159 Code style changes due to black version update.
  src/flownet/ahm/_ahm_iteration_analytics.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/network_model/_one_dimensional_model.py
  src/flownet/parameters/_equilibration.py
  src/flownet/parameters/_porv_poro_trans.py
  src/flownet/prediction/_run_pred.py
  src/flownet/realization/_schedule.py
  src/flownet/realization/_simulation_realization.py
Labels: maintenance

#157 I156 new perf strat
  CHANGELOG.md
  src/flownet/data/from_flow.py
  tests/test_one_dimensional.py
Labels: enhancement

#162 Fixes a bug where too many parameters would be created for satnum/eqlnum
  src/flownet/ahm/_run_ahm.py
  src/flownet/network_model/_generate_connections.py
Labels: bug

#147 Observation vectors in config yaml
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
Labels: enhancement

#167 Don't use pyscal 0.6.0+ for the time being
  setup.py
Labels: bug

#175 Remove cache from Github workflow
  .github/workflows/flownet.yml
Labels: bug, maintenance

#181 Remove conda from install instructions
  README.md
Labels: documentation

#182 Return CLI help if no arguments supplied to flownet
  src/flownet/_command_line.py
Labels: bug

#186 Speed up schedule creation
  src/flownet/realization/_schedule.py
  src/flownet/realization/_simulation_keywords.py
Labels: maintenance

#160 Use source model EQLNUM region when generating a FlowNet
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/network_model/_network_model.py
  src/flownet/parameters/_equilibration.py
  src/flownet/templates/EQUIL.jinja2
Labels: enhancement

#187 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, maintenance

#188 Use source model SATNUM regions when generating a FlowNet
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
Labels: enhancement

#191 Reduce pylint configuration file
  .pylintrc
  src/flownet/realization/__init__.py
  src/flownet/realization/_render_realization.py
  src/flownet/realization/_simulation_realization.py
Labels: maintenance

#194 Add PYTHONWARNINGS to CI
  .github/workflows/flownet.yml
Labels: maintenance

#127 Enables the prescription of a distribution mean from a previous HM
  .github/workflows/flownet.yml
  src/flownet/_command_line.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/parameters/_base_parameter.py
  src/flownet/parameters/probability_distributions.py
Labels: enhancement
