Repository equinor/flownet, pull requests merged in 2020-12, with the labels that each got.

#271 Add timer to kill ERT if no output for 15 minutes
  setup.py
  src/flownet/ert/_run_subprocess.py
Labels: invalid

#262 Improve performance of analytics workflow
  src/flownet/ahm/_ahm_iteration_analytics.py
  tests/test_save_plots_metrics.py
Labels: enhancement, invalid

#275 Add vscode to gitignore
  .gitignore
Labels: maintenance

#272 Adds resampling of observations
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/__init__.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
  tests/test_check_obsfiles_ert_yaml.py
Labels: enhancement

#288 Pin xrld to <2.0 to avoid version conflixt with semeio
  setup.py
Labels: maintenance

#251 Adding probability distribution options
  .gitignore
  CHANGELOG.md
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/parameters/_aquifer.py
  src/flownet/parameters/_base_parameter.py
  src/flownet/parameters/_equilibration.py
  src/flownet/parameters/_fault_transmissibility.py
  src/flownet/parameters/_porv_poro_trans.py
  src/flownet/parameters/_relative_permeability.py
  src/flownet/parameters/probability_distributions.py
  tests/test_probability_distributions.py
Labels: enhancement
