Repository equinor/flownet, pull requests merged in 2020-11, with the labels that each got.

#238 Fixes analysis workflow for flat BHP in Egg model
  src/flownet/ahm/_ahm_iteration_analytics.py
  tests/test_normalize_data.py
Labels: bug

#236 Generating low/base/high SCAL recommendations for pyscal
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
Labels: bug

#247 Fixes usage of lists in yaml analysis config
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/templates/ahm_config.ert.jinja2
Labels: invalid

#234 Add experiment tracking using mlflow
  .github/workflows/flownet.yml
  CHANGELOG.md
  setup.py
  src/flownet/_command_line.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/__init__.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/config_parser/_config_parser_hyperparam.py
  src/flownet/hyperparameter/__init__.py
  src/flownet/hyperparameter/_run_hyper.py
Labels: enhancement

#228 Install all Python dependencies from PyPI
  .github/workflows/flownet.yml
  CHANGELOG.md
  README.md
  build_environment.sh
  setup.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/config_parser/_config_parser_pred.py
  src/flownet/ert/FLOW_SIMULATION
  src/flownet/ert/_flow_job.py
  src/flownet/templates/common_config.ert.jinja2
Labels: enhancement, maintenance

#256 Fix duplicate names in hyperopt parameters by using full yaml path
  CHANGELOG.md
  src/flownet/config_parser/_config_parser_hyperparam.py
Labels: bug

#246 Issue #235 mitchell 2D
  src/flownet/network_model/_mitchell.py
  tests/test_mitchell.py
Labels: enhancement, maintenance

#259 Report parameters early in mflow + print exceptions in hyperopt runs
  src/flownet/hyperparameter/_run_hyper.py
Labels: enhancement

#249 Makes analysis workflow robust against failed simulations
  src/flownet/ahm/_ahm_iteration_analytics.py
Labels: bug

#264 Add posibility to create empty schedule
  src/flownet/realization/_schedule.py
Labels: enhancement

#227 Add export of training, test, and complete observation files
  src/flownet/ert/__init__.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/realization/_schedule.py
  src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
  src/flownet/templates/ahm_config.ert.jinja2
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
  src/flownet/templates/webviz_ahm_config.yml.jinja2
  tests/observation_files/ProductionData.csv
  tests/test_check_obsfiles_ert_yaml.py
Labels: enhancement

#270 Raise SubprocessError for non-zero returncode of the ERT subprocess
  src/flownet/ert/_run_subprocess.py
Labels: invalid
