Repository equinor/flownet, pull requests merged in 2020-04, with the labels that each got.

#18 Add build badge and bump pyscal to fix dependency issue
  README.md
  setup.py
Labels: bug, documentation

#21 Deploy to PyPI on releases
  .github/workflows/flownet.yml
  README.md
  setup.py
Labels: enhancement

#20 Setting faults as 'None' when the model has no faults
  src/flownet/network_model/_network_model.py
Labels: bug

#23 Improve README and documentation
  README.md
  docs/_static/flownet_logo.png
  docs/_static/flownet_logo.svg
  docs/conf.py
Labels: documentation
