Repository equinor/flownet, pull requests merged in 2020-07, with the labels that each got.

#63 Rename Eclipse to Flow
  examples/flow_model_import.py
  examples/norne_parameters.yml
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/__init__.py
  src/flownet/data/from_flow.py
  src/flownet/network_model/_create_egrid.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_one_dimensional_model.py
  src/flownet/parameters/_equilibration.py
  src/flownet/parameters/_relative_permeability.py
  src/flownet/realization/_render_realization.py
  src/flownet/realization/_schedule.py
  src/flownet/realization/_simulation_realization.py
  src/flownet/utils/write_grdecl_file.py
  tests/configs/norne_parameters.yml
  tests/test_flow_import.py
Labels: documentation

#93 Use pandas 1.0
  setup.py
  src/flownet/network_model/_network_model.py
  src/flownet/realization/_schedule.py
Labels: maintenance

#97 Add AllowNone for relative permeability and training_set_end_date
  src/flownet/config_parser/_config_parser.py
Labels: bug

#95 Add early check for training set definition
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  tests/configs/norne_parameters.yml
Labels: invalid

#91 Update GitHub actions workflow
  .github/workflows/flownet.yml
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/data/from_flow.py
  src/flownet/prediction/_run_pred.py
Labels: maintenance
