Repository equinor/flownet, pull requests merged in 2021-05, with the labels that each got.

#393 Make SATNUM regions in FlowNet based on region parameter from simulation model
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
Labels: enhancement

#396 Make EQLNUM regions in FlowNet based on region parameter from simulation model
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
Labels: enhancement

#398 Solve deprecation warning: remove .Required in config parser
  src/flownet/config_parser/_config_parser.py
Labels: invalid

#403 Only print THPRES between neighboring equil regions
  CHANGELOG.md
  src/flownet/parameters/_equilibration.py
  src/flownet/templates/THPRES.jinja2
Labels: bug

#380 I377 Mitchell's speed up
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_hull.py
  src/flownet/network_model/_mitchell.py
  tests/test_generate_connections.py
  tests/test_mitchell.py
Labels: enhancement

#407 Fix LGTM warnings
  src/flownet/config_parser/_config_parser.py
  src/flownet/config_parser/_config_parser_pred.py
  src/flownet/ert/forward_models/_iteration_analytics.py
  src/flownet/parameters/probability_distributions.py
Labels: invalid

#404 Make regional multipliers for bulkvolume, porosity and permeability
  .github/workflows/flownet.yml
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_porv_poro_trans.py
Labels: enhancement
