Repository equinor/flownet, pull requests merged in 2021-02, with the labels that each got.

#321 Fast mode in relative permeability interpolation option
  setup.py
  src/flownet/parameters/_relative_permeability.py
Labels: enhancement

#308 corrects a time shift in the FlowNet schedule relative to data
  src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
Labels: bug

#322 Support for separate RSVD tables in equilibration regions
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_equilibration.py
  src/flownet/templates/RSVD.jinja2
Labels: enhancement

#325 Fix for numerical sorting of iterations
  CHANGELOG.md
  src/flownet/ahm/_ahm_iteration_analytics.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_hull.py
  src/flownet/network_model/_network_model.py
Labels: bug

#334 Fix pylint errors after new version
  src/flownet/network_model/_generate_connections.py
  tests/test_generate_connections.py
  tests/test_normalize_data.py
Labels: maintenance

#337 Added option to run multiple analytics workflows during history matching
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/hyperparameter/_run_hyper.py
  src/flownet/static/SAVE_ITERATION_ANALYTICS_WORKFLOW
  src/flownet/templates/SAVE_ITERATION_ANALYTICS_WORKFLOW.jinja2
  src/flownet/templates/ahm_config.ert.jinja2
Labels: enhancement

#339 Fix analytics workflow to work with wellname filters again
  CHANGELOG.md
  src/flownet/ahm/_ahm_iteration_analytics.py
Labels: bug

#341 Add option to remove flow path if permeability is below a threshold
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_porv_poro_trans.py
Labels: enhancement

#344 Fixes to PR for i278
  src/flownet/parameters/_relative_permeability.py
Labels: invalid

#342 Changed additional flow node input to list to allow various from layer to layer
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
Labels: enhancement

#331 Fix high memory usage when using individual option for relative permeability
  src/flownet/parameters/_relative_permeability.py
Labels: bug

#345 Update changelog for 0.5.0 release
  CHANGELOG.md
Labels: maintenance
