Repository equinor/flownet, pull requests merged in 2021-03, with the labels that each got.

#346 Fixes bug where the analytics module would fail for iterations > 9
  CHANGELOG.md
  src/flownet/ahm/_ahm_iteration_analytics.py
Labels: bug

#347 i343_Allow a single number to be entered for the number of additional flow nodes
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
Labels: invalid

#351 Add simple plotting tool
  CHANGELOG.md
  setup.py
  src/flownet/utils/observations.py
  src/flownet/utils/plot_results.py
  tests/test_check_obsfiles_ert_yaml.py
Labels: enhancement

#365 Analytics in prediction mode
  CHANGELOG.md
  setup.py
  src/flownet/ahm/__init__.py
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/config_parser/_config_parser_pred.py
  src/flownet/config_parser/_config_transformations.py
  src/flownet/data/from_flow.py
  src/flownet/data/from_source.py
  src/flownet/ert/_create_ert_setup.py
  src/flownet/ert/forward_models/FLOW_SIMULATION
  src/flownet/ert/forward_models/__init__.py
  src/flownet/ert/forward_models/_delete_simulation_output.py
  src/flownet/ert/forward_models/_flow_job.py
  src/flownet/ert/forward_models/_iteration_analytics.py
  src/flownet/ert/forward_models/_render_realization.py
  src/flownet/ert/forward_models/_save_iteration_parameters.py
  src/flownet/ert/forward_models/utils.py
  src/flownet/realization/__init__.py
  src/flownet/templates/SAVE_ITERATION_ANALYTICS_WORKFLOW.jinja2
  tests/test_calculation_accuracy_metric.py
  tests/test_data_flow.py
  tests/test_iteration_analytics.py
  tests/test_prepare_flownet_data.py
  tests/test_prepare_opm_ref_data.py
  tests/test_prepare_opm_reference_data.py
Labels: bug, enhancement

#363 Drop Python 3.6 support
  .github/workflows/flownet.yml
  CHANGELOG.md
  README.md
  setup.py
Labels: maintenance

#361 Faster generation of SWOF and SGOF
  .pylintrc
  CHANGELOG.md
  setup.py
  src/flownet/parameters/_relative_permeability.py
  tests/test_relative_permeability.py
Labels: enhancement

#374 Fix memory leak in result plotting script
  CHANGELOG.md
  src/flownet/utils/plot_results.py
Labels: bug
