Repository equinor/flownet, pull requests merged in 2021-01, with the labels that each got.

#293 bug when interpolate relperm is true
  src/flownet/ahm/_run_ahm.py
Labels: bug

#279 Add layer_id to each well connection
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/data/perforation_strategy.py
  tests/test_data_flow.py
Labels: enhancement

#294 Docstring changes
  src/flownet/parameters/_aquifer.py
  src/flownet/parameters/_equilibration.py
  src/flownet/parameters/_fault_transmissibility.py
  src/flownet/parameters/_porv_poro_trans.py
  src/flownet/parameters/_relative_permeability.py
Labels: documentation

#303 Update _run_ahm.py
  src/flownet/ahm/_run_ahm.py
Labels: bug

#296 i290 Adapt perforation strategy to layers
  CHANGELOG.md
  src/flownet/data/perforation_strategy.py
  tests/data/well_perforations_2layers.csv
  tests/test_perforation_strategies.py
Labels: enhancement

#298 Improved model generation
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_hull.py
  src/flownet/network_model/_mitchell.py
  src/flownet/realization/_schedule.py
  tests/test_generate_connections.py
Labels: enhancement

#302 Bug fix rel perm interpolation
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_relative_permeability.py
Labels: bug

#305 I276 enabled new layering functionality
  CHANGELOG.md
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/network_model/_generate_connections.py
  tests/test_data_flow.py
  tests/test_generate_connections.py
Labels: enhancement

#313 Bugfix: foreign connections of other wells now no longer taken into a…
  src/flownet/data/perforation_strategy.py
  tests/data/well_perforations_2layers.csv
  tests/test_perforation_strategies.py
Labels: bug
