Repository equinor/flownet, pull requests merged in 2021-04, with the labels that each got.

#372 Node placement in volume of original model
  src/flownet/config_parser/_config_parser.py
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_mitchell.py
  tests/test_generate_connections.py
  tests/test_mitchell.py
Labels: enhancement

#378 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#379 Add delta to SWL to calculate SWCR
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/parameters/_relative_permeability.py
Labels: enhancement

#356 Add option to distribute volume according to geometric distribution
  CHANGELOG.md
  setup.py
  src/flownet/ahm/_run_ahm.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/__init__.py
  src/flownet/data/from_flow.py
  src/flownet/network_model/_network_model.py
  src/flownet/parameters/_porv_poro_trans.py
  tests/data/df_entity_connections.csv
  tests/data/df_well_connections.csv
  tests/test_data_flow.py
Labels: enhancement

#384 Fix CI failing due to new version of pylint
  src/flownet/utils/observations.py
Labels: bug

#386 Expose FlowNet timeout to user and increase default timeout
  CHANGELOG.md
  src/flownet/ahm/_assisted_history_matching.py
  src/flownet/config_parser/_config_parser.py
  src/flownet/config_parser/_config_parser_pred.py
  src/flownet/ert/_run_subprocess.py
  src/flownet/prediction/_run_pred.py
Labels: enhancement, invalid

#391 Fix observation templates
  CHANGELOG.md
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
Labels: bug
