Repository equinor/flownet, pull requests merged in 2021-06, with the labels that each got.

#414 Add test requirements
  setup.py
Labels: bug, maintenance

#413 Fix issues related to generating a FlowNet from 2D input
  src/flownet/network_model/_generate_connections.py
  src/flownet/network_model/_network_model.py
Labels: bug, enhancement

#348 Documenting usage of yaml configuration file
  docs/configuration_file.rst
  docs/index.rst
Labels: documentation

#417 Add brine p
  CHANGELOG.md
  src/flownet/config_parser/_config_parser.py
  src/flownet/data/from_flow.py
  src/flownet/realization/_schedule.py
  src/flownet/realization/_simulation_keywords.py
  src/flownet/static/SUMMARY.inc
  src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
  src/flownet/templates/TEMPLATE_MODEL.DATA.jinja2
  src/flownet/templates/observations.ertobs.jinja2
  src/flownet/templates/observations.yamlobs.jinja2
  tests/test_check_obsfiles_ert_yaml.py
Labels: enhancement
